version: "3.9"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG=front:latest
    image: front:latest
    container_name: front
    ports:
      - "80:80"
    restart: always
    depends_on:
      - db
      - bg
    networks:
      - pika-network

  bg:
    build:
      context: ./bg
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG=bg:latest
    image: bg:latest
    container_name: bg
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db
    networks:
      - pika-network

  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - pika-network

networks:
  pika-network:
    driver: bridge

volumes:
  postgres_data: 
